from ...data.dataset.handler import DataHandlerLP
from ...data.dataset.processor import Processor
from ...utils import get_callable_kwargs
from ...data.dataset import processor as processor_module
from inspect import getfullargspec


def check_transform_proc(proc_l, fit_start_time, fit_end_time):
    new_l = []
    for p in proc_l:
        if not isinstance(p, Processor):
            klass, pkwargs = get_callable_kwargs(p, processor_module)
            args = getfullargspec(klass).args
            if "fit_start_time" in args and "fit_end_time" in args:
                assert (
                    fit_start_time is not None and fit_end_time is not None
                ), "Make sure `fit_start_time` and `fit_end_time` are not None."
                pkwargs.update(
                    {
                        "fit_start_time": fit_start_time,
                        "fit_end_time": fit_end_time,
                    }
                )
            proc_config = {"class": klass.__name__, "kwargs": pkwargs}
            if isinstance(p, dict) and "module_path" in p:
                proc_config["module_path"] = p["module_path"]
            new_l.append(proc_config)
        else:
            new_l.append(p)
    return new_l

_DEFAULT_LEARN_PROCESSORS = [
    {"class": "DropnaLabel"},
    {"class": "CSZScoreNorm", "kwargs": {"fields_group": "feature"}},
]
_DEFAULT_INFER_PROCESSORS = [
    {"class": "ProcessInf", "kwargs": {}},
    {"class": "ZScoreNorm", "kwargs": {}},
    {"class": "Fillna", "kwargs": {}},
]


class Alpha158(DataHandlerLP):
    def __init__(
        self,
        instruments="csi500",
        start_time=None,
        end_time=None,
        freq="day",
        infer_processors=[],
        learn_processors=_DEFAULT_LEARN_PROCESSORS,
        fit_start_time=None,
        fit_end_time=None,
        process_type=DataHandlerLP.PTYPE_A,
        filter_pipe=None,
        inst_processors=None,
        **kwargs
    ):
        infer_processors = check_transform_proc(infer_processors, fit_start_time, fit_end_time)
        learn_processors = check_transform_proc(learn_processors, fit_start_time, fit_end_time)

        data_loader = {
            "class": "QlibDataLoader",
            "kwargs": {
                "config": {
                    "feature": self.get_feature_config(),
                    "label": kwargs.pop("label", self.get_label_config()),
                },
                "filter_pipe": filter_pipe,
                "freq": freq,
                "inst_processors": inst_processors,
            },
        }

        print('Using custom alpha + manually defined + [20260115] ...')


        super().__init__(
            instruments=instruments,
            start_time=start_time,
            end_time=end_time,
            data_loader=data_loader,
            infer_processors=infer_processors,
            learn_processors=learn_processors,
            process_type=process_type,
            **kwargs
        )

    def get_feature_config(self):
        conf = {
            "kbar": {},
            "price": {},
            "volume": {},
            "feature_filter": {},
            "time_series": {},
            "gating": {},
        }
        return self.parse_config_to_fields(conf)

    def get_label_config(self):
        return ["Ref($adjclose, -5)/Ref($adjclose, -1) - 1"], ["LABEL0"]

    @staticmethod
    def parse_config_to_fields(config):
        col_list = [
            "$amount",
            "$d_hhi",
            "$d_intraday_trend",
            "$d_realized_vol",
            "$d_trades_close_corr",
            "$d_volatility_of_volume",
            "$high",
            "$high/($close+1e-12)",
            "$i_change_1",
            "$i_change_1_std_30",
            "$inc_book_per_share_ttm",
            "$inc_revenue_ttm",
            "$low/($close+1e-12)",
            "$market_cap",
            "$pb_ratio_ttm",
            "$peg_ratio_ttm",
            "$return_on_asset_net_profit_ttm",
            "$total_asset_turnover_ttm",
            "$turn/($turn_current_year+1e-12)",
            "$volume",
            "$volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12))",
            "($close-$open)/$open",
            "($high-Greater($open, $close))/$open",
            "($high-Greater($open, $close))/($high-$low+1e-12)",
            "(Less($open, $close)-$low)/$open",
            "(Less($open, $close)-$low)/($high-$low+1e-12)",
            "Corr($close, Log($amount + 1), 11)",
            "Corr($close, Log($amount + 1), 31)",
            "Corr($close, Log($close + 1), 61)",
            "Corr($close, Log($d_close_rank + 1), 11)",
            "Corr($close, Log($d_close_rank + 1), 23)",
            "Corr($close, Log($d_close_rank + 1), 31)",
            "Corr($close, Log($d_close_rank + 1), 5)",
            "Corr($close, Log($d_close_vwap + 1), 11)",
            "Corr($close, Log($d_close_vwap + 1), 5)",
            "Corr($close, Log($d_close_vwap + 1), 61)",
            "Corr($close, Log($d_cntn + 1), 61)",
            "Corr($close, Log($d_cntp + 1), 11)",
            "Corr($close, Log($d_cntp + 1), 31)",
            "Corr($close, Log($d_cntp + 1), 5)",
            "Corr($close, Log($d_dwr + 1), 11)",
            "Corr($close, Log($d_dwr + 1), 31)",
            "Corr($close, Log($d_dwr + 1), 5)",
            "Corr($close, Log($d_dwr + 1), 61)",
            "Corr($close, Log($d_hhi + 1), 5)",
            "Corr($close, Log($d_high_time_frac + 1), 5)",
            "Corr($close, Log($d_intraday_trend + 1), 23)",
            "Corr($close, Log($d_intraday_trend + 1), 31)",
            "Corr($close, Log($d_intraday_trend + 1), 61)",
            "Corr($close, Log($d_low_time_frac + 1), 11)",
            "Corr($close, Log($d_low_time_frac + 1), 5)",
            "Corr($close, Log($d_low_time_frac + 1), 61)",
            "Corr($close, Log($d_pm_vwap + 1), 23)",
            "Corr($close, Log($d_ret_kurt + 1), 11)",
            "Corr($close, Log($d_ret_kurt + 1), 61)",
            "Corr($close, Log($d_ret_skew + 1), 11)",
            "Corr($close, Log($d_ret_skew + 1), 5)",
            "Corr($close, Log($d_trades_close_corr + 1), 11)",
            "Corr($close, Log($d_trades_close_corr + 1), 5)",
            "Corr($close, Log($d_trades_close_corr + 1), 61)",
            "Corr($close, Log($d_trades_vol_corr + 1), 11)",
            "Corr($close, Log($d_trades_vol_corr + 1), 5)",
            "Corr($close, Log($d_vol + 1), 11)",
            "Corr($close, Log($d_vol + 1), 31)",
            "Corr($close, Log($d_vol + 1), 5)",
            "Corr($close, Log($d_vol_kurt + 1), 61)",
            "Corr($close, Log($d_vol_skew + 1), 11)",
            "Corr($close, Log($d_vol_skew + 1), 31)",
            "Corr($close, Log($d_vol_skew + 1), 5)",
            "Corr($close, Log($d_vwap + 1), 61)",
            "Corr($close, Log($high + 1), 11)",
            "Corr($close, Log($high + 1), 31)",
            "Corr($close, Log($open + 1), 5)",
            "Corr($close, Log($turn_current_year + 1), 11)",
            "Corr($close, Log($turn_current_year + 1), 23)",
            "Corr($close, Log($turn_current_year + 1), 5)",
            "Corr($close, Log($turn_current_year + 1), 61)",
            "Corr($close, Log($turn_month + 1), 11)",
            "Corr($close, Log($turn_month + 1), 23)",
            "Corr($close, Log($turn_month + 1), 5)",
            "Corr($close, Log($turn_month + 1), 61)",
            "Corr($close, Log($turn_week + 1), 5)",
            "Corr($close, Log($turn_year + 1), 11)",
            "Corr($close, Log($turn_year + 1), 31)",
            "Corr($close, Log($turn_year + 1), 5)",
            "Corr($close, Log($turn_year + 1), 61)",
            "Corr($close/Ref($close,1), Log($amount/Ref($amount, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($buy_volume/Ref($buy_volume, 1)+1), 31)",
            "Corr($close/Ref($close,1), Log($buy_volume/Ref($buy_volume, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($buy_volume/Ref($buy_volume, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_close_rank/Ref($d_close_rank, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_close_rank/Ref($d_close_rank, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_close_rank/Ref($d_close_rank, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_close_vwap/Ref($d_close_vwap, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_cntn/Ref($d_cntn, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_cntp/Ref($d_cntp, 1)+1), 31)",
            "Corr($close/Ref($close,1), Log($d_cntp/Ref($d_cntp, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_corr/Ref($d_corr, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_corr/Ref($d_corr, 1)+1), 31)",
            "Corr($close/Ref($close,1), Log($d_corr/Ref($d_corr, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_corr/Ref($d_corr, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_dwr/Ref($d_dwr, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_dwr/Ref($d_dwr, 1)+1), 23)",
            "Corr($close/Ref($close,1), Log($d_dwr/Ref($d_dwr, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_hhi/Ref($d_hhi, 1)+1), 31)",
            "Corr($close/Ref($close,1), Log($d_hhi/Ref($d_hhi, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_high_time_frac/Ref($d_high_time_frac, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_high_time_frac/Ref($d_high_time_frac, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_high_time_frac/Ref($d_high_time_frac, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_intraday_trend/Ref($d_intraday_trend, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_intraday_trend/Ref($d_intraday_trend, 1)+1), 23)",
            "Corr($close/Ref($close,1), Log($d_intraday_trend/Ref($d_intraday_trend, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_low_time_frac/Ref($d_low_time_frac, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_low_time_frac/Ref($d_low_time_frac, 1)+1), 23)",
            "Corr($close/Ref($close,1), Log($d_low_time_frac/Ref($d_low_time_frac, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_low_time_frac/Ref($d_low_time_frac, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_pm_vwap/Ref($d_pm_vwap, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_realized_vol/Ref($d_realized_vol, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_ret_kurt/Ref($d_ret_kurt, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_ret_skew/Ref($d_ret_skew, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_ret_skew/Ref($d_ret_skew, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_trades_close_corr/Ref($d_trades_close_corr, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_trades_close_corr/Ref($d_trades_close_corr, 1)+1), 31)",
            "Corr($close/Ref($close,1), Log($d_trades_close_corr/Ref($d_trades_close_corr, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_trades_close_corr/Ref($d_trades_close_corr, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_trades_vol_corr/Ref($d_trades_vol_corr, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_trades_vol_corr/Ref($d_trades_vol_corr, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_trades_vol_corr/Ref($d_trades_vol_corr, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_vol/Ref($d_vol, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_vol_skew/Ref($d_vol_skew, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_vol_skew/Ref($d_vol_skew, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_vol_skew/Ref($d_vol_skew, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($d_vwap/Ref($d_vwap, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($d_vwap/Ref($d_vwap, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($d_vwap/Ref($d_vwap, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($high/Ref($high, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($high/Ref($high, 1)+1), 23)",
            "Corr($close/Ref($close,1), Log($high/Ref($high, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($low/Ref($low, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($low/Ref($low, 1)+1), 23)",
            "Corr($close/Ref($close,1), Log($low/Ref($low, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($low/Ref($low, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($open/Ref($open, 1)+1), 11)",
            "Corr($close/Ref($close,1), Log($open/Ref($open, 1)+1), 23)",
            "Corr($close/Ref($close,1), Log($open/Ref($open, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($open/Ref($open, 1)+1), 61)",
            "Corr($close/Ref($close,1), Log($turn_month/Ref($turn_month, 1)+1), 5)",
            "Corr($close/Ref($close,1), Log($turn_year/Ref($turn_year, 1)+1), 5)",
            "Max($high, 61)/$close",
            "Mean($buy_amount, 11)/($buy_amount + 1e-12)",
            "Mean($buy_amount>Ref($buy_amount, 1), 11)",
            "Mean($buy_amount>Ref($buy_amount, 1), 61)",
            "Mean($buy_volume>Ref($buy_volume, 1), 23)",
            "Mean($close, 61)/($close + 1e-12)",
            "Mean($d_close_rank<Ref($d_close_rank, 1), 31)",
            "Mean($d_close_rank<Ref($d_close_rank, 1), 61)",
            "Mean($d_close_rank>Ref($d_close_rank, 1), 11)-Mean($d_close_rank<Ref($d_close_rank, 1), 11)",
            "Mean($d_close_rank>Ref($d_close_rank, 1), 61)",
            "Mean($d_close_rank>Ref($d_close_rank, 1), 61)-Mean($d_close_rank<Ref($d_close_rank, 1), 61)",
            "Mean($d_cntn<Ref($d_cntn, 1), 61)",
            "Mean($d_cntn>Ref($d_cntn, 1), 11)-Mean($d_cntn<Ref($d_cntn, 1), 11)",
            "Mean($d_cntn>Ref($d_cntn, 1), 23)-Mean($d_cntn<Ref($d_cntn, 1), 23)",
            "Mean($d_cntn>Ref($d_cntn, 1), 61)",
            "Mean($d_cntp<Ref($d_cntp, 1), 31)",
            "Mean($d_cntp<Ref($d_cntp, 1), 61)",
            "Mean($d_cntp>Ref($d_cntp, 1), 23)-Mean($d_cntp<Ref($d_cntp, 1), 23)",
            "Mean($d_cntp>Ref($d_cntp, 1), 61)",
            "Mean($d_corr, 11)/($d_corr + 1e-12)",
            "Mean($d_corr>Ref($d_corr, 1), 23)",
            "Mean($d_corr>Ref($d_corr, 1), 61)",
            "Mean($d_dwr, 11)/($d_dwr + 1e-12)",
            "Mean($d_dwr, 5)/($d_dwr + 1e-12)",
            "Mean($d_dwr<Ref($d_dwr, 1), 11)",
            "Mean($d_dwr<Ref($d_dwr, 1), 23)",
            "Mean($d_dwr<Ref($d_dwr, 1), 61)",
            "Mean($d_hhi<Ref($d_hhi, 1), 11)",
            "Mean($d_hhi<Ref($d_hhi, 1), 5)",
            "Mean($d_hhi<Ref($d_hhi, 1), 61)",
            "Mean($d_hhi>Ref($d_hhi, 1), 31)-Mean($d_hhi<Ref($d_hhi, 1), 31)",
            "Mean($d_high_time_frac<Ref($d_high_time_frac, 1), 11)",
            "Mean($d_high_time_frac<Ref($d_high_time_frac, 1), 5)",
            "Mean($d_high_time_frac<Ref($d_high_time_frac, 1), 61)",
            "Mean($d_high_time_frac>Ref($d_high_time_frac, 1), 11)",
            "Mean($d_high_time_frac>Ref($d_high_time_frac, 1), 23)-Mean($d_high_time_frac<Ref($d_high_time_frac, 1), 23)",
            "Mean($d_high_time_frac>Ref($d_high_time_frac, 1), 61)",
            "Mean($d_high_time_frac>Ref($d_high_time_frac, 1), 61)-Mean($d_high_time_frac<Ref($d_high_time_frac, 1), 61)",
            "Mean($d_intraday_trend, 23)/($d_intraday_trend + 1e-12)",
            "Mean($d_intraday_trend, 61)/($d_intraday_trend + 1e-12)",
            "Mean($d_intraday_trend<Ref($d_intraday_trend, 1), 11)",
            "Mean($d_intraday_trend<Ref($d_intraday_trend, 1), 23)",
            "Mean($d_intraday_trend<Ref($d_intraday_trend, 1), 61)",
            "Mean($d_intraday_trend>Ref($d_intraday_trend, 1), 5)-Mean($d_intraday_trend<Ref($d_intraday_trend, 1), 5)",
            "Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 11)",
            "Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 31)",
            "Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 61)",
            "Mean($d_low_time_frac>Ref($d_low_time_frac, 1), 11)-Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 11)",
            "Mean($d_low_time_frac>Ref($d_low_time_frac, 1), 23)",
            "Mean($d_low_time_frac>Ref($d_low_time_frac, 1), 23)-Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 23)",
            "Mean($d_low_time_frac>Ref($d_low_time_frac, 1), 5)-Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 5)",
            "Mean($d_low_time_frac>Ref($d_low_time_frac, 1), 61)-Mean($d_low_time_frac<Ref($d_low_time_frac, 1), 61)",
            "Mean($d_realized_vol<Ref($d_realized_vol, 1), 61)",
            "Mean($d_ret_kurt<Ref($d_ret_kurt, 1), 5)",
            "Mean($d_ret_kurt>Ref($d_ret_kurt, 1), 11)",
            "Mean($d_ret_kurt>Ref($d_ret_kurt, 1), 31)",
            "Mean($d_ret_kurt>Ref($d_ret_kurt, 1), 61)",
            "Mean($d_ret_skew, 5)/($d_ret_skew + 1e-12)",
            "Mean($d_ret_skew<Ref($d_ret_skew, 1), 11)",
            "Mean($d_ret_skew<Ref($d_ret_skew, 1), 23)",
            "Mean($d_ret_skew<Ref($d_ret_skew, 1), 5)",
            "Mean($d_ret_skew<Ref($d_ret_skew, 1), 61)",
            "Mean($d_trades_close_corr, 5)/($d_trades_close_corr + 1e-12)",
            "Mean($d_trades_close_corr, 61)/($d_trades_close_corr + 1e-12)",
            "Mean($d_trades_close_corr>Ref($d_trades_close_corr, 1), 11)",
            "Mean($d_trades_close_corr>Ref($d_trades_close_corr, 1), 23)",
            "Mean($d_trades_close_corr>Ref($d_trades_close_corr, 1), 5)",
            "Mean($d_trades_close_corr>Ref($d_trades_close_corr, 1), 61)",
            "Mean($d_trades_vol_corr<Ref($d_trades_vol_corr, 1), 11)",
            "Mean($d_trades_vol_corr>Ref($d_trades_vol_corr, 1), 31)",
            "Mean($d_trades_vol_corr>Ref($d_trades_vol_corr, 1), 61)",
            "Mean($d_vol<Ref($d_vol, 1), 11)",
            "Mean($d_vol>Ref($d_vol, 1), 23)-Mean($d_vol<Ref($d_vol, 1), 23)",
            "Mean($d_vol_kurt<Ref($d_vol_kurt, 1), 11)",
            "Mean($d_vol_kurt<Ref($d_vol_kurt, 1), 5)",
            "Mean($d_vol_kurt<Ref($d_vol_kurt, 1), 61)",
            "Mean($d_vol_kurt>Ref($d_vol_kurt, 1), 31)",
            "Mean($d_vol_skew<Ref($d_vol_skew, 1), 61)",
            "Mean($d_vol_skew>Ref($d_vol_skew, 1), 31)-Mean($d_vol_skew<Ref($d_vol_skew, 1), 31)",
            "Mean($d_volatility_of_volume>Ref($d_volatility_of_volume, 1), 23)",
            "Mean($num_trades>Ref($num_trades, 1), 23)",
            "Mean($turn_current_year>Ref($turn_current_year, 1), 61)",
            "Mean($turn_week>Ref($turn_week, 1), 61)",
            "Mean($turn_year, 5)/($turn_year + 1e-12)",
            "Mean($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 11)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Mean($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12))>Ref($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 1), 31)",
            "Mean($vwap, 11)/($vwap + 1e-12)",
            "Mean(($buy_volume*2-$volume)/($volume+1e-12)<Ref(($buy_volume*2-$volume)/($volume+1e-12), 1), 11)",
            "Mean(($buy_volume*2-$volume)/($volume+1e-12)>Ref(($buy_volume*2-$volume)/($volume+1e-12), 1), 61)",
            "Mean((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 11)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Mean((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 5)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Mean((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 61)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Mean((($buy_amount*2-$amount)*10000)/($market_cap+1e-12)<Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 1), 23)",
            "Mean((($buy_amount*2-$amount)*10000)/($market_cap+1e-12)<Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 1), 61)",
            "Min($low, 31)/$close",
            "Quantile($d_cntn, 11, 0.8)/($d_cntn + 1e-12)",
            "Quantile($d_hhi, 5, 0.8)/($d_hhi + 1e-12)",
            "Quantile($d_hhi, 61, 0.2)/($d_hhi + 1e-12)",
            "Quantile($d_high_time_frac, 11, 0.2)/($d_high_time_frac + 1e-12)",
            "Quantile($d_high_time_frac, 5, 0.2)/($d_high_time_frac + 1e-12)",
            "Quantile($d_intraday_trend, 11, 0.8)/($d_intraday_trend + 1e-12)",
            "Quantile($d_intraday_trend, 5, 0.8)/($d_intraday_trend + 1e-12)",
            "Quantile($d_low_time_frac, 11, 0.2)/($d_low_time_frac + 1e-12)",
            "Quantile($d_low_time_frac, 23, 0.2)/($d_low_time_frac + 1e-12)",
            "Quantile($d_low_time_frac, 5, 0.2)/($d_low_time_frac + 1e-12)",
            "Quantile($d_realized_vol, 11, 0.2)/($d_realized_vol + 1e-12)",
            "Quantile($d_realized_vol, 31, 0.2)/($d_realized_vol + 1e-12)",
            "Quantile($d_ret_kurt, 11, 0.8)/($d_ret_kurt + 1e-12)",
            "Quantile($d_ret_kurt, 23, 0.2)/($d_ret_kurt + 1e-12)",
            "Quantile($d_ret_skew, 11, 0.2)/($d_ret_skew + 1e-12)",
            "Quantile($d_ret_skew, 61, 0.2)/($d_ret_skew + 1e-12)",
            "Quantile($d_trades_close_corr, 5, 0.2)/($d_trades_close_corr + 1e-12)",
            "Quantile($d_trades_vol_corr, 23, 0.2)/($d_trades_vol_corr + 1e-12)",
            "Quantile($d_trades_vol_corr, 23, 0.8)/($d_trades_vol_corr + 1e-12)",
            "Quantile($d_trades_vol_corr, 5, 0.2)/($d_trades_vol_corr + 1e-12)",
            "Quantile($turn_month, 5, 0.2)/($turn_month + 1e-12)",
            "Quantile($turn_week, 11, 0.2)/($turn_week + 1e-12)",
            "Quantile($volume, 61, 0.2)/($volume + 1e-12)",
            "Rank($d_ret_kurt, 23)",
            "Rank($d_ret_skew, 11)",
            "Rank($turn_month, 61)",
            "Rank(($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12))), 61)",
            "Ref($buy_amount, 5)/($buy_amount+1e-12)",
            "Ref($d_close_rank, 11)/($d_close_rank+1e-12)",
            "Ref($d_close_rank, 23)/($d_close_rank+1e-12)",
            "Ref($d_close_rank, 31)/($d_close_rank+1e-12)",
            "Ref($d_close_rank, 5)/($d_close_rank+1e-12)",
            "Ref($d_close_rank, 61)/($d_close_rank+1e-12)",
            "Ref($d_cntn, 5)/($d_cntn+1e-12)",
            "Ref($d_cntn, 61)/($d_cntn+1e-12)",
            "Ref($d_cntp, 11)/($d_cntp+1e-12)",
            "Ref($d_cntp, 5)/($d_cntp+1e-12)",
            "Ref($d_corr, 31)/($d_corr+1e-12)",
            "Ref($d_corr, 5)/($d_corr+1e-12)",
            "Ref($d_corr, 61)/($d_corr+1e-12)",
            "Ref($d_dwr, 11)/($d_dwr+1e-12)",
            "Ref($d_dwr, 23)/($d_dwr+1e-12)",
            "Ref($d_dwr, 31)/($d_dwr+1e-12)",
            "Ref($d_dwr, 5)/($d_dwr+1e-12)",
            "Ref($d_dwr, 61)/($d_dwr+1e-12)",
            "Ref($d_hhi, 11)/($d_hhi+1e-12)",
            "Ref($d_hhi, 23)/($d_hhi+1e-12)",
            "Ref($d_hhi, 31)/($d_hhi+1e-12)",
            "Ref($d_high_time_frac, 23)/($d_high_time_frac+1e-12)",
            "Ref($d_high_time_frac, 5)/($d_high_time_frac+1e-12)",
            "Ref($d_high_time_frac, 61)/($d_high_time_frac+1e-12)",
            "Ref($d_intraday_trend, 11)/($d_intraday_trend+1e-12)",
            "Ref($d_intraday_trend, 23)/($d_intraday_trend+1e-12)",
            "Ref($d_intraday_trend, 31)/($d_intraday_trend+1e-12)",
            "Ref($d_intraday_trend, 5)/($d_intraday_trend+1e-12)",
            "Ref($d_intraday_trend, 61)/($d_intraday_trend+1e-12)",
            "Ref($d_low_time_frac, 11)/($d_low_time_frac+1e-12)",
            "Ref($d_low_time_frac, 23)/($d_low_time_frac+1e-12)",
            "Ref($d_low_time_frac, 31)/($d_low_time_frac+1e-12)",
            "Ref($d_low_time_frac, 61)/($d_low_time_frac+1e-12)",
            "Ref($d_realized_vol, 5)/($d_realized_vol+1e-12)",
            "Ref($d_ret_skew, 11)/($d_ret_skew+1e-12)",
            "Ref($d_ret_skew, 23)/($d_ret_skew+1e-12)",
            "Ref($d_ret_skew, 31)/($d_ret_skew+1e-12)",
            "Ref($d_ret_skew, 5)/($d_ret_skew+1e-12)",
            "Ref($d_ret_skew, 61)/($d_ret_skew+1e-12)",
            "Ref($d_trades_close_corr, 11)/($d_trades_close_corr+1e-12)",
            "Ref($d_trades_close_corr, 23)/($d_trades_close_corr+1e-12)",
            "Ref($d_trades_vol_corr, 11)/($d_trades_vol_corr+1e-12)",
            "Ref($d_trades_vol_corr, 23)/($d_trades_vol_corr+1e-12)",
            "Ref($d_trades_vol_corr, 31)/($d_trades_vol_corr+1e-12)",
            "Ref($d_trades_vol_corr, 5)/($d_trades_vol_corr+1e-12)",
            "Ref($d_trades_vol_corr, 61)/($d_trades_vol_corr+1e-12)",
            "Ref($d_vol, 61)/($d_vol+1e-12)",
            "Ref($d_vol_cv, 61)/($d_vol_cv+1e-12)",
            "Ref($d_vol_skew, 5)/($d_vol_skew+1e-12)",
            "Ref($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 11)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Ref($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 5)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Ref($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 61)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Ref(($buy_volume*2-$volume)/($volume+1e-12), 11)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Ref(($buy_volume*2-$volume)/($volume+1e-12), 31)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Ref(($buy_volume*2-$volume)/($volume+1e-12), 61)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 11)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 23)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 31)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 5)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Ref((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 61)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Resi($buy_amount, 5)/($buy_amount + 1e-12)",
            "Resi($close, 11)/($close + 1e-12)",
            "Resi($close, 23)/($close + 1e-12)",
            "Resi($close, 5)/($close + 1e-12)",
            "Resi($d_close_rank, 5)/($d_close_rank + 1e-12)",
            "Resi($d_cntn, 5)/($d_cntn + 1e-12)",
            "Resi($d_cntn, 61)/($d_cntn + 1e-12)",
            "Resi($d_cntp, 11)/($d_cntp + 1e-12)",
            "Resi($d_cntp, 5)/($d_cntp + 1e-12)",
            "Resi($d_corr, 5)/($d_corr + 1e-12)",
            "Resi($d_dwr, 5)/($d_dwr + 1e-12)",
            "Resi($d_hhi, 5)/($d_hhi + 1e-12)",
            "Resi($d_intraday_trend, 11)/($d_intraday_trend + 1e-12)",
            "Resi($d_intraday_trend, 31)/($d_intraday_trend + 1e-12)",
            "Resi($d_intraday_trend, 5)/($d_intraday_trend + 1e-12)",
            "Resi($d_low_time_frac, 5)/($d_low_time_frac + 1e-12)",
            "Resi($d_ret_kurt, 5)/($d_ret_kurt + 1e-12)",
            "Resi($d_ret_skew, 5)/($d_ret_skew + 1e-12)",
            "Resi($d_trades_vol_corr, 5)/($d_trades_vol_corr + 1e-12)",
            "Resi($d_vol, 5)/($d_vol + 1e-12)",
            "Resi($d_vol_skew, 11)/($d_vol_skew + 1e-12)",
            "Resi($open, 5)/($open + 1e-12)",
            "Resi($open, 61)/($open + 1e-12)",
            "Resi($turn_current_year, 61)/($turn_current_year + 1e-12)",
            "Resi($turn_month, 11)/($turn_month + 1e-12)",
            "Resi($turn_month, 31)/($turn_month + 1e-12)",
            "Resi($turn_month, 5)/($turn_month + 1e-12)",
            "Resi($turn_week, 11)/($turn_week + 1e-12)",
            "Resi($turn_week, 5)/($turn_week + 1e-12)",
            "Resi($turn_week, 61)/($turn_week + 1e-12)",
            "Resi($turn_year, 11)/($turn_year + 1e-12)",
            "Resi($turn_year, 31)/($turn_year + 1e-12)",
            "Resi($turn_year, 5)/($turn_year + 1e-12)",
            "Resi($turn_year, 61)/($turn_year + 1e-12)",
            "Resi($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 5)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Resi(($buy_volume*2-$volume)/($volume+1e-12), 5)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Resi((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 5)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Rsquare($amount, 61)/($amount + 1e-12)",
            "Rsquare($d_close_rank, 11)/($d_close_rank + 1e-12)",
            "Rsquare($d_close_rank, 23)/($d_close_rank + 1e-12)",
            "Rsquare($d_close_rank, 31)/($d_close_rank + 1e-12)",
            "Rsquare($d_close_rank, 5)/($d_close_rank + 1e-12)",
            "Rsquare($d_close_rank, 61)/($d_close_rank + 1e-12)",
            "Rsquare($d_cntn, 11)/($d_cntn + 1e-12)",
            "Rsquare($d_cntn, 31)/($d_cntn + 1e-12)",
            "Rsquare($d_cntn, 5)/($d_cntn + 1e-12)",
            "Rsquare($d_cntp, 11)/($d_cntp + 1e-12)",
            "Rsquare($d_cntp, 5)/($d_cntp + 1e-12)",
            "Rsquare($d_dwr, 5)/($d_dwr + 1e-12)",
            "Rsquare($d_hhi, 11)/($d_hhi + 1e-12)",
            "Rsquare($d_hhi, 23)/($d_hhi + 1e-12)",
            "Rsquare($d_hhi, 31)/($d_hhi + 1e-12)",
            "Rsquare($d_hhi, 5)/($d_hhi + 1e-12)",
            "Rsquare($d_intraday_trend, 5)/($d_intraday_trend + 1e-12)",
            "Rsquare($d_realized_vol, 61)/($d_realized_vol + 1e-12)",
            "Rsquare($d_ret_kurt, 11)/($d_ret_kurt + 1e-12)",
            "Rsquare($d_ret_kurt, 31)/($d_ret_kurt + 1e-12)",
            "Rsquare($d_ret_kurt, 5)/($d_ret_kurt + 1e-12)",
            "Rsquare($d_ret_kurt, 61)/($d_ret_kurt + 1e-12)",
            "Rsquare($d_ret_skew, 5)/($d_ret_skew + 1e-12)",
            "Rsquare($d_trades_close_corr, 31)/($d_trades_close_corr + 1e-12)",
            "Rsquare($d_trades_vol_corr, 11)/($d_trades_vol_corr + 1e-12)",
            "Rsquare($d_trades_vol_corr, 23)/($d_trades_vol_corr + 1e-12)",
            "Rsquare($d_trades_vol_corr, 31)/($d_trades_vol_corr + 1e-12)",
            "Rsquare($d_trades_vol_corr, 5)/($d_trades_vol_corr + 1e-12)",
            "Rsquare($d_trades_vol_corr, 61)/($d_trades_vol_corr + 1e-12)",
            "Rsquare($d_vol, 11)/($d_vol + 1e-12)",
            "Rsquare($d_vol, 23)/($d_vol + 1e-12)",
            "Rsquare($d_vol, 31)/($d_vol + 1e-12)",
            "Rsquare($d_vol, 5)/($d_vol + 1e-12)",
            "Rsquare($d_vol_cv, 61)/($d_vol_cv + 1e-12)",
            "Rsquare($d_vol_kurt, 11)/($d_vol_kurt + 1e-12)",
            "Rsquare($d_vol_kurt, 23)/($d_vol_kurt + 1e-12)",
            "Rsquare($d_vol_kurt, 31)/($d_vol_kurt + 1e-12)",
            "Rsquare($d_vol_kurt, 5)/($d_vol_kurt + 1e-12)",
            "Rsquare($d_vol_kurt, 61)/($d_vol_kurt + 1e-12)",
            "Rsquare($turn_week, 23)/($turn_week + 1e-12)",
            "Rsquare($turn_week, 61)/($turn_week + 1e-12)",
            "Rsquare($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 11)",
            "Rsquare($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 23)",
            "Rsquare($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 31)",
            "Rsquare($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 5)",
            "Rsquare($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 61)",
            "Rsquare($volume, 11)/($volume + 1e-12)",
            "Rsquare($volume, 23)/($volume + 1e-12)",
            "Rsquare($volume, 61)/($volume + 1e-12)",
            "Rsquare((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 11)",
            "Rsquare((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 23)",
            "Rsquare((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 31)",
            "Rsquare((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 5)",
            "Rsquare((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 61)",
            "Slope($d_close_rank, 11)/($d_close_rank + 1e-12)",
            "Slope($d_close_rank, 23)/($d_close_rank + 1e-12)",
            "Slope($d_close_rank, 31)/($d_close_rank + 1e-12)",
            "Slope($d_close_rank, 5)/($d_close_rank + 1e-12)",
            "Slope($d_close_rank, 61)/($d_close_rank + 1e-12)",
            "Slope($d_cntn, 11)/($d_cntn + 1e-12)",
            "Slope($d_cntn, 5)/($d_cntn + 1e-12)",
            "Slope($d_cntn, 61)/($d_cntn + 1e-12)",
            "Slope($d_cntp, 11)/($d_cntp + 1e-12)",
            "Slope($d_cntp, 31)/($d_cntp + 1e-12)",
            "Slope($d_cntp, 5)/($d_cntp + 1e-12)",
            "Slope($d_corr, 31)/($d_corr + 1e-12)",
            "Slope($d_corr, 61)/($d_corr + 1e-12)",
            "Slope($d_dwr, 11)/($d_dwr + 1e-12)",
            "Slope($d_dwr, 23)/($d_dwr + 1e-12)",
            "Slope($d_dwr, 31)/($d_dwr + 1e-12)",
            "Slope($d_dwr, 5)/($d_dwr + 1e-12)",
            "Slope($d_dwr, 61)/($d_dwr + 1e-12)",
            "Slope($d_hhi, 11)/($d_hhi + 1e-12)",
            "Slope($d_hhi, 5)/($d_hhi + 1e-12)",
            "Slope($d_intraday_trend, 11)/($d_intraday_trend + 1e-12)",
            "Slope($d_intraday_trend, 23)/($d_intraday_trend + 1e-12)",
            "Slope($d_intraday_trend, 31)/($d_intraday_trend + 1e-12)",
            "Slope($d_intraday_trend, 5)/($d_intraday_trend + 1e-12)",
            "Slope($d_intraday_trend, 61)/($d_intraday_trend + 1e-12)",
            "Slope($d_low_time_frac, 11)/($d_low_time_frac + 1e-12)",
            "Slope($d_low_time_frac, 23)/($d_low_time_frac + 1e-12)",
            "Slope($d_low_time_frac, 31)/($d_low_time_frac + 1e-12)",
            "Slope($d_low_time_frac, 5)/($d_low_time_frac + 1e-12)",
            "Slope($d_low_time_frac, 61)/($d_low_time_frac + 1e-12)",
            "Slope($d_realized_vol, 11)/($d_realized_vol + 1e-12)",
            "Slope($d_ret_kurt, 11)/($d_ret_kurt + 1e-12)",
            "Slope($d_ret_kurt, 23)/($d_ret_kurt + 1e-12)",
            "Slope($d_ret_kurt, 5)/($d_ret_kurt + 1e-12)",
            "Slope($d_ret_kurt, 61)/($d_ret_kurt + 1e-12)",
            "Slope($d_ret_skew, 11)/($d_ret_skew + 1e-12)",
            "Slope($d_ret_skew, 23)/($d_ret_skew + 1e-12)",
            "Slope($d_ret_skew, 31)/($d_ret_skew + 1e-12)",
            "Slope($d_ret_skew, 5)/($d_ret_skew + 1e-12)",
            "Slope($d_ret_skew, 61)/($d_ret_skew + 1e-12)",
            "Slope($d_trades_close_corr, 11)/($d_trades_close_corr + 1e-12)",
            "Slope($d_trades_close_corr, 23)/($d_trades_close_corr + 1e-12)",
            "Slope($d_trades_close_corr, 5)/($d_trades_close_corr + 1e-12)",
            "Slope($d_trades_vol_corr, 11)/($d_trades_vol_corr + 1e-12)",
            "Slope($d_trades_vol_corr, 23)/($d_trades_vol_corr + 1e-12)",
            "Slope($d_trades_vol_corr, 5)/($d_trades_vol_corr + 1e-12)",
            "Slope($d_trades_vol_corr, 61)/($d_trades_vol_corr + 1e-12)",
            "Slope($d_vol_cv, 31)/($d_vol_cv + 1e-12)",
            "Slope($d_vol_cv, 61)/($d_vol_cv + 1e-12)",
            "Slope($d_vol_skew, 23)/($d_vol_skew + 1e-12)",
            "Slope($open, 61)/($open + 1e-12)",
            "Slope($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 11)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Slope($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 31)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Slope(($buy_volume*2-$volume)/($volume+1e-12), 11)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Slope(($buy_volume*2-$volume)/($volume+1e-12), 23)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Slope(($buy_volume*2-$volume)/($volume+1e-12), 5)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Slope(($buy_volume*2-$volume)/($volume+1e-12), 61)/(($buy_volume*2-$volume)/($volume+1e-12))",
            "Slope((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 11)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Slope((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 23)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Slope((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 31)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Slope((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 5)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Slope((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 61)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Std($buy_amount, 11)/($buy_amount + 1e-12)",
            "Std($buy_amount, 23)/($buy_amount + 1e-12)",
            "Std($buy_volume, 5)/($buy_volume + 1e-12)",
            "Std($d_cntn, 5)/($d_cntn + 1e-12)",
            "Std($d_hhi, 31)/($d_hhi + 1e-12)",
            "Std($d_hhi, 5)/($d_hhi + 1e-12)",
            "Std($d_hhi, 61)/($d_hhi + 1e-12)",
            "Std($d_vol, 31)/($d_vol + 1e-12)",
            "Std($d_vol_cv, 31)/($d_vol_cv + 1e-12)",
            "Std($d_vol_cv, 5)/($d_vol_cv + 1e-12)",
            "Std($d_vol_kurt, 5)/($d_vol_kurt + 1e-12)",
            "Std($d_vol_skew, 61)/($d_vol_skew + 1e-12)",
            "Std($turn_current_year, 11)/($turn_current_year + 1e-12)",
            "Std($turn_current_year, 23)/($turn_current_year + 1e-12)",
            "Std($turn_month, 11)/($turn_month + 1e-12)",
            "Std($turn_month, 23)/($turn_month + 1e-12)",
            "Std($turn_week, 11)/($turn_week + 1e-12)",
            "Std($turn_week, 5)/($turn_week + 1e-12)",
            "Std($turn_year, 11)/($turn_year + 1e-12)",
            "Std($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)), 31)/($volume*10000/($num_trades+1e-12)/($market_cap/($close+1e-12)))",
            "Std((($buy_amount*2-$amount)*10000)/($market_cap+1e-12), 5)/((($buy_amount*2-$amount)*10000)/($market_cap+1e-12))",
            "Std(Abs($close/Ref($close, 1)-1)*$volume, 11)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 11)+1e-12)",
            "Std(Abs($close/Ref($close, 1)-1)*$volume, 5)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 5)+1e-12)",
            "Std(Abs($close/Ref($close, 1)-1)*$volume, 61)/(Mean(Abs($close/Ref($close, 1)-1)*$volume, 61)+1e-12)",
            "Sum(Greater($volume-Ref($volume, 1), 0), 61)/(Sum(Abs($volume-Ref($volume, 1)), 61)+1e-12)",
            "$i_change_1_mean_5",
            "$i_change_1_std_5",
        ]       
        fields = col_list
        names = col_list
        
        
        return fields, names


class Alpha158vwap(Alpha158):
    def get_label_config(self):
        return ["Ref($adjclose, -5) / Ref($adjclose, -1) - 1"], ["Ref($adjclose, -5) / Ref($adjclose, -1) - 1"]